import { readFile } from 'node:fs/promises';
import { resolve, relative, dirname } from 'node:path';
import { unified } from 'unified';
import remarkParse from 'remark-parse';
import remarkStringify from 'remark-stringify';
import { visit } from 'unist-util-visit';
import type { Code, Paragraph, Image, Link, Root, Html } from 'mdast';
import type { Parent } from 'unist';
import type { ExtractedBlock, ParseResult } from './types.js';
import { parseMeta } from './renderer.js';

const AURA_LANG = 'aura';

export async function parseSource(
  sourcePath: string,
  assetsDir = '.github/assets',
  outputPath = 'README.md',
): Promise<ParseResult> {
  const source = await readFile(sourcePath, 'utf-8');
  const blocks: ExtractedBlock[] = [];
  let blockIndex = 0;

  // Compute asset path relative to the output file
  const absAssets = resolve(assetsDir);
  const absOutput = resolve(outputPath);
  const relAssets = './' + relative(dirname(absOutput), absAssets).replace(/\\/g, '/');

  const file = await unified()
    .use(remarkParse)
    .use(() => (tree: Root) => {
      visit(tree, 'code', (node, index, parent: Parent | undefined) => {
        const codeNode = node as Code;
        if (codeNode.lang !== AURA_LANG || index === undefined || !parent) return;

        blocks.push({
          index: blockIndex,
          content: codeNode.value,
          meta: codeNode.meta ?? undefined,
        });

        const { link, inline } = parseMeta(codeNode.meta ?? undefined);

        if (inline) {
          const htmlNode: Html = {
            type: 'html',
            value: `<!-- __AURA_INLINE_${blockIndex}__ -->`,
          };
          (parent.children as unknown[])[index] = htmlNode;
        } else {
          const imageNode: Image = {
            type: 'image',
            url: `${relAssets}/readme-aura-component-${blockIndex}.svg`,
            alt: `readme-aura-component-${blockIndex}`,
            title: 'Generated by readme-aura',
          };

          const paragraphChild = link
            ? ({ type: 'link', url: link, children: [imageNode] } as Link)
            : imageNode;

          const paragraphNode: Paragraph = {
            type: 'paragraph',
            children: [paragraphChild],
          };

          (parent.children as unknown[])[index] = paragraphNode;
        }
        blockIndex++;
      });
    })
    .use(remarkStringify)
    .process(source);

  // Merge consecutive inline placeholders: remove blank lines between them
  // so they end up on one line and GitHub renders them as inline elements.
  let md = String(file);
  let prev: string;
  do {
    prev = md;
    md = md.replace(
      /(<!-- __AURA_INLINE_\d+__ -->)\n\n(<!-- __AURA_INLINE_\d+__ -->)/g,
      '$1$2',
    );
  } while (md !== prev);

  return {
    markdown: md,
    blocks,
    relAssets,
  };
}
